# database container
db:
  image: docker.io/mysql
  ports:
    - "4306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=password

# applicaiton container
app:
  image: docker.io/tomcat
  ports:
    - "9080:8080"

# web container
web:
  image: docker.io/nginx
  ports:
    - "90:80"
